import { test, expect } from "@playwright/test";
import {
  buildAdmin,
  contextForUser,
  provisionUser,
  cleanupEphemeralUsers
} from "./_setup/personas";

// Customer journey end-to-end against the live deploy.
// Anonymous funnel: landing → talk-to-lawyer lead → triage → docs →
// free PDF download. Then authed: account/inbox welcome notification,
// referrals, UPI intent.

const TS = Date.now();
const CUSTOMER_EMAIL = `qa-cust+${TS}@legaldesk-test.ai`;

test.describe.configure({ mode: "serial" });

test.describe("customer journey", () => {
  test("1. landing renders the three primary CTAs", async ({ page }) => {
    await page.goto("/");
    await expect(
      page.getByRole("link", { name: /Talk to a lawyer/i }).first()
    ).toBeVisible();
    await expect(
      page.getByRole("link", { name: /Start free triage/i }).first()
    ).toBeVisible();
    await expect(
      page.getByRole("link", { name: /Browse documents/i }).first()
    ).toBeVisible();
  });

  let leadId: string | null = null;
  test("2. anonymous /talk-to-lawyer lead capture writes a row", async ({
    request
  }) => {
    const res = await request.post("/api/consult-leads", {
      data: {
        name: `QA Customer ${TS}`,
        phone: "+919999900001",
        issue:
          "My landlord refused to refund my deposit of Rs 50000 after I vacated the flat three months ago in good condition."
      }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.ok).toBe(true);
    expect(body.lead_id).toBeTruthy();
    expect(body.callback_eta).toContain("10");
    leadId = body.lead_id;
  });

  test("3. anonymous /triage classifies a query and renders Case Prep", async ({
    page
  }) => {
    await page.goto("/triage");
    await page
      .getByLabel(
        "Describe your legal situation in plain language. Hindi or English is fine."
      )
      .fill(
        "My landlord refused to refund my deposit of Rs 50000 after I vacated the flat."
      );
    await page.getByRole("button", { name: /Run triage/i }).click();
    await expect(page.getByText(/Initial classification/i)).toBeVisible({
      timeout: 30_000
    });
    await expect(
      page.getByRole("heading", { name: "Case Prep", exact: true })
    ).toBeVisible({ timeout: 30_000 });
    await expect(
      page.getByText(/Generated by LegalDesk AI\. Not legal advice\./i)
    ).toBeVisible();
  });

  test("4. anonymous /documents/legal-notice downloads a real PDF", async ({
    request
  }) => {
    const res = await request.post(
      "/api/documents/legal-notice/download?format=pdf",
      {
        data: {
          sender: {
            name: "QA Customer",
            address: "45 Yari Road, Andheri West, Mumbai 400053"
          },
          recipient: {
            name: "Acme Properties LLP",
            address: "Andheri East, Mumbai 400069"
          },
          cause: {
            date_of_event: "2026-04-01",
            place: "Mumbai",
            description:
              "Deposit of Rs 50000 not refunded after the flat was vacated in good condition."
          },
          demand: {
            summary: "Refund the security deposit of Rs 50000 in full.",
            deadline_days: 15
          }
        }
      }
    );
    expect(res.status()).toBe(200);
    expect(res.headers()["content-type"]).toContain("application/pdf");
    const bytes = await res.body();
    expect(bytes.slice(0, 4).toString("utf8")).toBe("%PDF");
    expect(bytes.byteLength).toBeGreaterThan(1000);
  });

  test("5. /pricing shows all tier cards", async ({ page }) => {
    await page.goto("/pricing");
    await expect(page.getByText(/Triage/i).first()).toBeVisible();
    await expect(page.getByText(/Plus/i).first()).toBeVisible();
  });

  test("6. provision + sign in as an ephemeral customer", async ({
    browser,
    baseURL
  }) => {
    const admin = buildAdmin();
    const userId = await provisionUser(admin, CUSTOMER_EMAIL);
    expect(userId).toBeTruthy();
    const ctx = await contextForUser(browser, baseURL!, CUSTOMER_EMAIL);
    const page = await ctx.newPage();
    const probe = await page.request.get("/api/dpdp/export");
    expect(probe.status()).toBe(200);
    await ctx.close();
  });

  test("7. authed /account/inbox shows the welcome notification", async ({
    browser,
    baseURL
  }) => {
    const ctx = await contextForUser(browser, baseURL!, CUSTOMER_EMAIL);
    const page = await ctx.newPage();
    await page.goto("/account/inbox");
    await expect(page.getByText(/Welcome to LegalDesk AI/i).first()).toBeVisible({
      timeout: 15_000
    });
    await ctx.close();
  });

  test("8. authed /account shows DPDP rights surface", async ({
    browser,
    baseURL
  }) => {
    const ctx = await contextForUser(browser, baseURL!, CUSTOMER_EMAIL);
    const page = await ctx.newPage();
    await page.goto("/account");
    const html = (await page.content()).toLowerCase();
    expect(html).toMatch(/export|download.*data|copy of/i);
    expect(html).toMatch(/delete|erase/i);
    await ctx.close();
  });

  test("9. authed /referrals exposes a referral code", async ({
    browser,
    baseURL
  }) => {
    const ctx = await contextForUser(browser, baseURL!, CUSTOMER_EMAIL);
    const page = await ctx.newPage();
    const res = await page.request.get("/api/referrals/me");
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(typeof body.code).toBe("string");
    expect(body.code.length).toBeGreaterThanOrEqual(4);
    await ctx.close();
  });

  test("10. teardown — delete the ephemeral customer + lead", async () => {
    const admin = buildAdmin();
    if (leadId) {
      await admin.from("consultation_leads").delete().eq("id", leadId);
    }
    await cleanupEphemeralUsers(admin);
  });
});
