import { test, expect } from "@playwright/test";

// End-to-end authenticated flows against the live deploy. Auth state
// is loaded from the storage.json captured by tests/e2e/_setup/auth.setup.ts.

test.describe("authenticated /triage flow", () => {
  test("submitting a query renders the structured Case Prep with disclaimer", async ({
    page
  }) => {
    await page.goto("/triage");
    await expect(page.getByText(/Tell us what happened\./i)).toBeVisible();

    const textarea = page.getByLabel(
      "Describe your legal situation in plain language. Hindi or English is fine."
    );
    await textarea.fill(
      "My landlord has not returned my deposit of Rs 50,000 even three months after I vacated the flat in Mumbai."
    );

    await page.getByRole("button", { name: /Run triage/i }).click();

    await expect(page.getByText(/Initial classification/i)).toBeVisible({
      timeout: 30_000
    });
    await expect(
      page.getByRole("heading", { name: "Case Prep", exact: true })
    ).toBeVisible({ timeout: 30_000 });
    await expect(
      page.getByText(/Generated by LegalDesk AI\. Not legal advice\./i)
    ).toBeVisible();
  });
});

test.describe("authenticated /documents flow", () => {
  test("legal-notice form fills and previews", async ({ page }) => {
    await page.goto("/documents/legal-notice");
    await expect(page.getByRole("heading", { name: /Legal notice/i })).toBeVisible();

    await page.getByLabel(/Full name \*/i).first().fill("Brij Kishor Singh");
    await page
      .getByLabel(/Address \*/i)
      .first()
      .fill("45 Yari Road, Andheri West, Mumbai 400053");

    await page.getByLabel(/Full name \*/i).nth(1).fill("Acme Properties LLP");
    await page
      .getByLabel(/Address \*/i)
      .nth(1)
      .fill("Andheri East, Mumbai 400069");

    await page.getByLabel(/Date of event \*/i).fill("2026-04-01");
    await page.getByLabel(/Place \*/i).fill("Mumbai");
    await page
      .getByLabel(/Describe what happened, in plain language \*/i)
      .fill(
        "Failure to refund the security deposit of Rs 50,000 paid at the start of the tenancy."
      );

    await page
      .getByLabel(/What action are you demanding\? \*/i)
      .fill("Refund the security deposit of Rs 50,000 in full.");
    await page.getByLabel(/Deadline \(days from receipt\) \*/i).fill("15");

    await page.getByRole("button", { name: /Preview document/i }).click();

    await expect(
      page.getByRole("heading", { name: "LEGAL NOTICE", exact: true })
    ).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText(/Subject: Legal Notice/i)).toBeVisible();
  });

  test("documents index lists every SKU", async ({ page }) => {
    await page.goto("/documents");
    await expect(page.getByRole("link", { name: /Legal notice/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /Reply to legal notice/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /Rent agreement/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /Consumer complaint/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /RTI application/i }).first()).toBeVisible();
  });
});

test.describe("authenticated /account DPDP surface", () => {
  test("account page shows the rights links", async ({ page }) => {
    await page.goto("/account");
    await expect(page).toHaveURL(/\/account/);
    const body = await page.content();
    expect(body.toLowerCase()).toMatch(/export|download.*data|copy of/i);
    expect(body.toLowerCase()).toMatch(/delete|erase/i);
  });
});

test.describe("authenticated /referrals", () => {
  test("renders a referral code for the user", async ({ page }) => {
    await page.goto("/referrals");
    await expect(page).toHaveURL(/\/referrals/);
    // Code is short (Crockford base32, 6 chars) — check the page has some
    // copy + something that looks like a code.
    const body = await page.content();
    expect(body.toLowerCase()).toContain("referral");
  });
});

test.describe("authenticated APIs", () => {
  test("/api/triage/classify returns a classification", async ({ request }) => {
    const res = await request.post("/api/triage/classify", {
      data: {
        raw_text:
          "My employer has not paid my salary for two months and is asking me to resign."
      }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(typeof body.classification).toBe("string");
    expect(["criminal", "civil", "family", "property", "consumer", "labour", "corporate", "tax", "cyber", "other"]).toContain(body.classification);
  });

  test("/api/dpdp/export returns the user's data envelope", async ({ request }) => {
    const res = await request.get("/api/dpdp/export");
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.ok).toBe(true);
    expect(body.export).toBeDefined();
    expect(body.export).toHaveProperty("queries");
    expect(body.export).toHaveProperty("documents");
    expect(body.export).toHaveProperty("wallet_ledger");
  });
});
