import { test, expect } from "@playwright/test";

// End-to-end authenticated flows against the live deploy. Auth state
// is loaded from the storage.json captured by tests/e2e/_setup/auth.setup.ts.

test.describe("authenticated /triage flow", () => {
  test("submitting a query renders the structured Case Prep with disclaimer", async ({
    page
  }) => {
    await page.goto("/triage");
    await expect(page.getByText(/Tell us what happened\./i)).toBeVisible();

    const textarea = page.getByLabel(
      "Describe your legal situation in plain language. Hindi or English is fine."
    );
    await textarea.fill(
      "My landlord has not returned my deposit of Rs 50,000 even three months after I vacated the flat in Mumbai."
    );

    await page.getByRole("button", { name: /Run triage/i }).click();

    await expect(page.getByText(/Initial classification/i)).toBeVisible({
      timeout: 30_000
    });
    await expect(
      page.getByRole("heading", { name: "Case Prep", exact: true })
    ).toBeVisible({ timeout: 30_000 });
    await expect(
      page.getByText(/Generated by LegalDesk AI\. Not legal advice\./i)
    ).toBeVisible();
  });
});

test.describe("authenticated /documents flow", () => {
  test("legal-notice form -> preview -> free download (PDF + DOCX)", async ({ page }) => {
    await page.goto("/documents/legal-notice");

    await page.getByLabel(/Full name \*/i).first().fill("Brij Kishor Singh");
    await page.getByLabel(/Address \*/i).first().fill("45 Yari Road, Andheri West, Mumbai 400053");
    await page.getByLabel(/Full name \*/i).nth(1).fill("Acme Properties LLP");
    await page.getByLabel(/Address \*/i).nth(1).fill("Andheri East, Mumbai 400069");
    await page.getByLabel(/Date of event \*/i).fill("2026-04-01");
    await page.getByLabel(/Place \*/i).fill("Mumbai");
    await page
      .getByLabel(/Describe what happened, in plain language \*/i)
      .fill(
        "Failure to refund the security deposit of Rs 50,000 paid at the start of the tenancy."
      );
    await page
      .getByLabel(/What action are you demanding\? \*/i)
      .fill("Refund the security deposit of Rs 50,000 in full.");
    await page.getByLabel(/Deadline \(days from receipt\) \*/i).fill("15");

    await page.getByRole("button", { name: /Preview document/i }).click();
    await expect(
      page.getByRole("heading", { name: "LEGAL NOTICE", exact: true })
    ).toBeVisible({ timeout: 30_000 });

    // PDF download
    const pdfDownload = page.waitForEvent("download", { timeout: 30_000 });
    await page.getByRole("button", { name: /Download as PDF/i }).click();
    const pdfFile = await pdfDownload;
    expect(pdfFile.suggestedFilename()).toMatch(/\.pdf$/i);
    const pdfPath = await pdfFile.path();
    expect(pdfPath, "PDF should have a path on disk").toBeTruthy();
    const fs = await import("node:fs/promises");
    const pdfBytes = await fs.readFile(pdfPath!);
    // Real PDF files start with the %PDF- magic header.
    expect(pdfBytes.slice(0, 4).toString("utf8")).toBe("%PDF");
    expect(pdfBytes.length).toBeGreaterThan(1000);

    // DOCX download
    const docxDownload = page.waitForEvent("download", { timeout: 30_000 });
    await page.getByRole("button", { name: /Download as DOCX/i }).click();
    const docxFile = await docxDownload;
    expect(docxFile.suggestedFilename()).toMatch(/\.docx$/i);
    const docxPath = await docxFile.path();
    expect(docxPath, "DOCX should have a path on disk").toBeTruthy();
    const docxBytes = await fs.readFile(docxPath!);
    // DOCX is a zip archive — the magic header is "PK\x03\x04".
    expect(docxBytes.slice(0, 2).toString("utf8")).toBe("PK");
    expect(docxBytes.length).toBeGreaterThan(1000);
  });

  test("legal-notice form fills and previews", async ({ page }) => {
    await page.goto("/documents/legal-notice");
    await expect(page.getByRole("heading", { name: /Legal notice/i })).toBeVisible();

    await page.getByLabel(/Full name \*/i).first().fill("Brij Kishor Singh");
    await page
      .getByLabel(/Address \*/i)
      .first()
      .fill("45 Yari Road, Andheri West, Mumbai 400053");

    await page.getByLabel(/Full name \*/i).nth(1).fill("Acme Properties LLP");
    await page
      .getByLabel(/Address \*/i)
      .nth(1)
      .fill("Andheri East, Mumbai 400069");

    await page.getByLabel(/Date of event \*/i).fill("2026-04-01");
    await page.getByLabel(/Place \*/i).fill("Mumbai");
    await page
      .getByLabel(/Describe what happened, in plain language \*/i)
      .fill(
        "Failure to refund the security deposit of Rs 50,000 paid at the start of the tenancy."
      );

    await page
      .getByLabel(/What action are you demanding\? \*/i)
      .fill("Refund the security deposit of Rs 50,000 in full.");
    await page.getByLabel(/Deadline \(days from receipt\) \*/i).fill("15");

    await page.getByRole("button", { name: /Preview document/i }).click();

    await expect(
      page.getByRole("heading", { name: "LEGAL NOTICE", exact: true })
    ).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText(/Subject: Legal Notice/i)).toBeVisible();
  });

  test("documents index lists every SKU", async ({ page }) => {
    await page.goto("/documents");
    await expect(page.getByRole("link", { name: /Legal notice/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /Reply to legal notice/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /Rent agreement/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /Consumer complaint/i }).first()).toBeVisible();
    await expect(page.getByRole("link", { name: /RTI application/i }).first()).toBeVisible();
  });
});

test.describe("authenticated /account DPDP surface", () => {
  test("account page shows the rights links", async ({ page }) => {
    await page.goto("/account");
    await expect(page).toHaveURL(/\/account/);
    const body = await page.content();
    expect(body.toLowerCase()).toMatch(/export|download.*data|copy of/i);
    expect(body.toLowerCase()).toMatch(/delete|erase/i);
  });
});

test.describe("authenticated /referrals", () => {
  test("renders a referral code for the user", async ({ page }) => {
    await page.goto("/referrals");
    await expect(page).toHaveURL(/\/referrals/);
    // Code is short (Crockford base32, 6 chars) — check the page has some
    // copy + something that looks like a code.
    const body = await page.content();
    expect(body.toLowerCase()).toContain("referral");
  });
});

test.describe("authenticated APIs", () => {
  test("/api/triage/classify returns a classification", async ({ request }) => {
    const res = await request.post("/api/triage/classify", {
      data: {
        raw_text:
          "My employer has not paid my salary for two months and is asking me to resign."
      }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(typeof body.classification).toBe("string");
    expect(["criminal", "civil", "family", "property", "consumer", "labour", "corporate", "tax", "cyber", "other"]).toContain(body.classification);
  });

  test("/api/triage/classify handles Hindi (देवनागरी) input", async ({ request }) => {
    const res = await request.post("/api/triage/classify", {
      data: {
        raw_text:
          "मेरे मकान मालिक ने मेरी जमा राशि 50,000 रुपये तीन महीने बाद भी वापस नहीं की है।"
      }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(typeof body.classification).toBe("string");
    expect(["criminal", "civil", "family", "property", "consumer", "labour", "corporate", "tax", "cyber", "other"]).toContain(body.classification);
    // Language detection should pick up Hindi from the script.
    if (body.language) {
      expect(["hi", "en"]).toContain(body.language);
    }
  });

  test("/api/dpdp/export returns the user's data envelope", async ({ request }) => {
    const res = await request.get("/api/dpdp/export");
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.ok).toBe(true);
    expect(body.export).toBeDefined();
    expect(body.export).toHaveProperty("queries");
    expect(body.export).toHaveProperty("documents");
    expect(body.export).toHaveProperty("wallet_ledger");
  });

  test("/api/consultations/book creates a draft + order", async ({ request }) => {
    const res = await request.post("/api/consultations/book", {
      data: {
        pack: "p15",
        channel: "call",
        specialization: "consumer",
        language: "en",
        state: "Maharashtra"
      }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.ok).toBe(true);
    expect(body.consultation_id).toBeTruthy();
    // Zero lawyers in the prod DB right now, so the matcher returns 0
    // candidates. The booking itself still succeeds.
    expect(typeof body.matched).toBe("number");
    // Real Razorpay order id when keys are wired, deterministic mock id
    // at Tier-0. Either is acceptable.
    expect(typeof body.order_id).toBe("string");
    expect(body.amount_paise).toBe(199_00);
  });

  test("/api/consultations/book rejects invalid input with 400", async ({ request }) => {
    const res = await request.post("/api/consultations/book", {
      data: { pack: "not-a-pack", channel: "call", specialization: "x", language: "y", state: "Z" }
    });
    expect(res.status()).toBe(400);
  });

  test("/api/lawyer/apply persists an application", async ({ request }) => {
    const res = await request.post("/api/lawyer/apply", {
      data: {
        bar_council_id: `KAR/QA/${Date.now()}`,
        state: "Karnataka",
        years_exp: 7,
        specializations: ["consumer", "civil"],
        languages: ["en", "hi"],
        pan: "ABCDE1234F",
        consent: true,
        payout: {
          legal_business_name: "QA Bot Advocates",
          contact_name: "QA Bot",
          contact_email: "qa-bot@legaldesk-test.ai",
          contact_phone: "+919999999999",
          upi_vpa: "qabot@upi"
        }
      }
    });
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.ok).toBe(true);
    expect(body.lawyer_id).toBeTruthy();
    expect(body.anon_slug).toMatch(/^[0-9a-f]{8,}$/);
    expect(body.status).toBe("pending");
  });

  test("/api/documents/[sku]/download returns a real PDF for valid input", async ({
    request
  }) => {
    const res = await request.post(
      "/api/documents/legal-notice/download?format=pdf",
      {
        data: {
          sender: {
            name: "Brij Kishor Singh",
            address: "45 Yari Road, Andheri West, Mumbai 400053"
          },
          recipient: {
            name: "Acme Properties LLP",
            address: "Andheri East, Mumbai 400069"
          },
          cause: {
            date_of_event: "2026-04-01",
            place: "Mumbai",
            description:
              "Failure to refund the security deposit of Rs 50,000 paid at the start of the tenancy."
          },
          demand: {
            summary: "Refund the security deposit of Rs 50,000 in full.",
            deadline_days: 15
          }
        }
      }
    );
    expect(res.status()).toBe(200);
    expect(res.headers()["content-type"]).toContain("application/pdf");
    expect(res.headers()["content-disposition"]).toContain("attachment");
    const bytes = await res.body();
    expect(bytes.slice(0, 4).toString("utf8")).toBe("%PDF");
    expect(bytes.byteLength).toBeGreaterThan(1000);
  });

  test("/api/documents/[sku]/download returns a real DOCX for valid input", async ({
    request
  }) => {
    const res = await request.post(
      "/api/documents/rti-application/download?format=docx",
      {
        data: {
          applicant: {
            name: "Brij Kishor Singh",
            address: "45 Yari Road, Andheri West, Mumbai 400053",
            phone: "+919999999999",
            is_indian_citizen: true,
            is_bpl: false
          },
          public_authority: {
            name: "Municipal Commissioner, BMC",
            address: "Mahapalika Marg, Mumbai 400001"
          },
          subject: "Request for status of pothole repair complaints",
          information_sought: [
            "How many pothole complaints were filed in Ward H/West in 2025?",
            "How many of those were resolved within 15 days?"
          ],
          period: { from: "2025-01-01", to: "2025-12-31" }
        }
      }
    );
    expect(res.status()).toBe(200);
    expect(res.headers()["content-type"]).toContain("wordprocessingml.document");
    const bytes = await res.body();
    expect(bytes.slice(0, 2).toString("utf8")).toBe("PK");
    expect(bytes.byteLength).toBeGreaterThan(1000);
  });

  test("/api/documents/[sku]/download rejects invalid format with 400", async ({
    request
  }) => {
    const res = await request.post(
      "/api/documents/legal-notice/download?format=xls",
      { data: {} }
    );
    expect(res.status()).toBe(400);
  });

  test("/api/lawyer/apply rejects missing payout details with 400", async ({ request }) => {
    const res = await request.post("/api/lawyer/apply", {
      data: {
        bar_council_id: "KAR/QA/missing",
        state: "Karnataka",
        years_exp: 3,
        specializations: ["consumer"],
        languages: ["en"],
        payout: {
          legal_business_name: "QA",
          contact_name: "QA",
          contact_email: "qa@legaldesk-test.ai",
          contact_phone: "+919999999999"
        }
      }
    });
    expect(res.status()).toBe(400);
  });
});
