import { test, expect } from "@playwright/test";

// Golden path 1: triage -> document preview.
//
// In mock mode (no Supabase / Anthropic keys) the triage routes return
// deterministic stubs and /triage renders the same UI it would in
// production, with auth gating bypassed via the "mock mode" banner.

test.describe("triage to document", () => {
  test("classifies a query and renders the structured Case Prep", async ({ page }) => {
    await page.goto("/triage");
    await expect(page.getByText("Tell us what happened.")).toBeVisible();

    const textarea = page.getByLabel(
      "Describe your legal situation in plain language. Hindi or English is fine."
    );
    await textarea.fill(
      "My landlord has not returned my deposit of Rs 50,000 even three months after I vacated the flat in Mumbai."
    );

    await page.getByRole("button", { name: /Run triage/i }).click();

    await expect(page.getByText(/Initial classification/i)).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText(/Case Prep/i)).toBeVisible({ timeout: 30_000 });
    await expect(
      page.getByText(/Generated by LegalDesk AI\. Not legal advice\./i)
    ).toBeVisible();
  });

  test("loads the legal-notice document page and previews", async ({ page }) => {
    await page.goto("/documents/legal-notice");
    await expect(page.getByRole("heading", { name: /Legal notice/i })).toBeVisible();

    // Sender
    await page.getByLabel(/Full name \*/i).first().fill("Brij Kishor Singh");
    await page.getByLabel(/Address \*/i).first().fill("45 Yari Road, Andheri West, Mumbai 400053");

    // Recipient
    await page.getByLabel(/Full name \*/i).nth(1).fill("Acme Properties LLP");
    await page.getByLabel(/Address \*/i).nth(1).fill("Andheri East, Mumbai 400069");

    // Cause
    await page.getByLabel(/Date of event \*/i).fill("2025-12-01");
    await page.getByLabel(/Place \*/i).fill("Mumbai");
    await page
      .getByLabel(/Describe what happened, in plain language \*/i)
      .fill(
        "Failure to refund the security deposit of Rs 50,000 paid at the start of the tenancy, despite the property being vacated and handed over in good condition."
      );

    // Demand
    await page
      .getByLabel(/What action are you demanding\? \*/i)
      .fill("Refund the security deposit of Rs 50,000 in full.");
    await page.getByLabel(/Deadline \(days from receipt\) \*/i).fill("15");

    await page.getByRole("button", { name: /Preview document/i }).click();

    await expect(page.getByRole("heading", { name: /Legal notice/i })).toBeVisible();
    await expect(page.getByText(/Subject: Legal Notice/i)).toBeVisible({ timeout: 15_000 });
    await expect(
      page.getByRole("button", { name: /Continue to payment/i })
    ).toBeVisible();
  });
});
