import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUserId } from "@/lib/triage/persistence";
import {
  getConsultationById,
  markCompleted,
  getLawyerByUserId
} from "@/lib/consult/persistence";
import { computePayoutSplit } from "@/lib/consult/packs";
import { summarizeTranscript } from "@/lib/consult/summarize";
import { sendEmail } from "@/lib/notify/email";
import { notifyUser } from "@/lib/notify/inbox";
import { getUserContact } from "@/lib/users/persistence";
import { getSupabaseServiceClient } from "@/lib/supabase/server";

export const runtime = "nodejs";

const Body = z.object({
  duration_sec: z.number().int().min(0).max(2 * 60 * 60),
  transcript: z.string().trim().min(0).max(50_000).optional(),
  transcript_url: z.string().url().optional()
});

const HOLD_HOURS = 24;

export async function POST(
  req: Request,
  { params }: { params: { id: string } }
) {
  const userId = await getCurrentUserId();
  if (!userId) {
    if (process.env.NEXT_PUBLIC_SUPABASE_URL) {
      return NextResponse.json({ error: "Sign in." }, { status: 401 });
    }
    return NextResponse.json({ ok: true, mock: true, summary: null });
  }
  let parsed: z.infer<typeof Body>;
  try {
    parsed = Body.parse(await req.json());
  } catch {
    return NextResponse.json({ error: "Invalid input." }, { status: 400 });
  }

  const c = await getConsultationById(params.id);
  if (!c) return NextResponse.json({ error: "Not found." }, { status: 404 });

  // Either party may finish.
  let canFinish = c.user_id === userId;
  if (!canFinish) {
    const lw = await getLawyerByUserId(userId);
    canFinish = !!lw && lw.id === c.lawyer_id;
  }
  if (!canFinish) return NextResponse.json({ error: "Forbidden." }, { status: 403 });

  let summary: string | null = null;
  if (parsed.transcript && parsed.transcript.length > 50) {
    try {
      summary = await summarizeTranscript({
        transcript: parsed.transcript,
        language: c.language ?? "en"
      });
    } catch (err) {
      console.error("[consult/finish] summarize failed", err);
    }
  }

  const split = computePayoutSplit(c.amount_inr);

  await markCompleted({
    consultationId: c.id,
    duration_sec: parsed.duration_sec,
    summary,
    transcript_url: parsed.transcript_url ?? null,
    payoutLawyerInrPaise: split.lawyer_payout_paise,
    payoutHoldHours: HOLD_HOURS
  });

  // Send the summary email to the user. Lawyer side gets a separate
  // notification when payout releases.
  const contact = await getUserContact(c.user_id);
  if (contact?.email && summary) {
    await sendEmail({
      to: contact.email,
      subject: "Your LegalDesk consult summary",
      html: `<p>Here is the summary of your consultation.</p><pre style="white-space:pre-wrap;font-family:inherit">${escapeHtml(
        summary
      )}</pre><p style="color:#666;font-size:12px;margin-top:24px">Generated by LegalDesk AI. Not legal advice. Consult a qualified advocate for case-specific opinion.</p>`
    });
  }

  // In-app notification for both parties — durable and live via Realtime.
  await notifyUser({
    userId: c.user_id,
    kind: "consultation.finished",
    title: "Consultation completed",
    body: summary ? "Summary is in your inbox." : "Thanks for using LegalDesk.",
    link: `/account`
  });
  const lawyerUserId = c.lawyer_id ? await lookupLawyerUserId(c.lawyer_id) : null;
  if (lawyerUserId) {
    await notifyUser({
      userId: lawyerUserId,
      kind: "consultation.finished",
      title: "Consultation completed",
      body: `Payout of Rs ${(split.lawyer_payout_paise / 100).toFixed(0)} held for 24h.`,
      link: `/lawyer`
    });
  }

  return NextResponse.json({
    ok: true,
    consultation_id: c.id,
    duration_sec: parsed.duration_sec,
    payout_lawyer_paise: split.lawyer_payout_paise,
    summary
  });
}

async function lookupLawyerUserId(lawyerId: string): Promise<string | null> {
  const supa = getSupabaseServiceClient();
  if (!supa) return null;
  const { data } = await supa
    .from("lawyers")
    .select("user_id")
    .eq("id", lawyerId)
    .maybeSingle();
  return (data?.user_id as string | undefined) ?? null;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
