import { createClient } from "@supabase/supabase-js";
import { getSupabaseServiceClient } from "@/lib/supabase/server";
import { notifyMany } from "@/lib/notify/inbox";

// Layered notification fanout for lawyer-facing events:
//   1. In-app + Web Push (already handled by notifyMany / notifyUser)
//   2. Email via Supabase's built-in mailer using a magic-link
//      generated by auth.admin.generateLink — works without any
//      third-party email API key. Rate-limited to 3/hour on the
//      Supabase free tier; fine for early-stage offer volume.
//
// The function below is the email-only layer; the in-app + push fanout
// happens in attachOffers/notifyMany.

interface EmailMagicLinkArgs {
  userId: string;
  subject: string;
  intro: string;
  nextPath: string;
}

export async function emailMagicLinkAlert(
  args: EmailMagicLinkArgs
): Promise<boolean> {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRole = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;
  if (!url || !serviceRole || !siteUrl) return false;

  const admin = createClient(url, serviceRole, {
    auth: { autoRefreshToken: false, persistSession: false }
  });

  // Look up the email.
  const supa = getSupabaseServiceClient();
  if (!supa) return false;
  const { data: u } = await supa
    .from("users")
    .select("email")
    .eq("id", args.userId)
    .maybeSingle();
  const email = u?.email;
  if (!email) return false;

  // Supabase's auth.admin.generateLink with type='magiclink' is the
  // path that triggers the built-in mailer. The subject + body are
  // configured in the project's Auth Emails template (we can refine
  // later via the Management API).
  try {
    const { error } = await admin.auth.admin.generateLink({
      type: "magiclink",
      email,
      options: {
        redirectTo: `${siteUrl}/auth/callback?next=${encodeURIComponent(
          args.nextPath
        )}`
      }
    });
    if (error) {
      if (/rate.?limit/i.test(error.message)) {
        // Expected on free tier; not actionable.
        return false;
      }
      console.warn("[lawyer-alerts] generateLink failed", error.message);
      return false;
    }
    return true;
  } catch (err) {
    console.warn("[lawyer-alerts] generateLink threw", err);
    return false;
  }
}

// Convenience wrapper used by attachOffers — fanout email to many
// lawyer user ids in parallel, returns count delivered (best-effort).
export async function emailManyLawyersOfNewOffer(
  lawyerUserIds: string[]
): Promise<number> {
  if (lawyerUserIds.length === 0) return 0;
  const results = await Promise.all(
    lawyerUserIds.map((id) =>
      emailMagicLinkAlert({
        userId: id,
        subject: "New consultation offer on LegalDesk",
        intro: "A client matching your profile just booked. First to accept wins.",
        nextPath: "/lawyer/offers"
      })
    )
  );
  return results.filter(Boolean).length;
}

// Also expose for the lawyer-side "click to message client on
// WhatsApp" once they accept. Zero-key — wa.me deep link with the
// client's phone number pre-filled.
export function waMeLinkFor(args: {
  clientPhone: string;
  text: string;
}): string {
  const phone = args.clientPhone.replace(/[^\d]/g, "");
  return `https://wa.me/${phone}?text=${encodeURIComponent(args.text)}`;
}
