import { getDocumentById, updateDocumentDelivered } from "@/lib/documents/persistence";
import { renderForSku } from "@/lib/templates";
import { renderDocumentPdf } from "@/lib/pdf/document-render";
import { renderDocumentDocx } from "@/lib/docx/document-render";
import { uploadDocumentArtefacts } from "@/lib/storage/documents";
import { sendEmail } from "@/lib/notify/email";
import { sendWhatsAppDocument } from "@/lib/notify/whatsapp";
import { createLawyerReview } from "@/lib/lawyer-reviews/persistence";
import { getUserContact } from "@/lib/users/persistence";

export interface FinalizeResult {
  finalized: boolean;
  pdfUrl: string | null;
  docxUrl: string | null;
  lawyerReviewId: string | null;
}

const UNFINALIZED: FinalizeResult = {
  finalized: false,
  pdfUrl: null,
  docxUrl: null,
  lawyerReviewId: null
};

// Renders, stores and delivers a paid document, and provisions the optional
// lawyer-review. Shared by the Razorpay webhook (payment.captured) and the
// admin UPI verify route so both capture paths deliver identically. Idempotent
// enough to re-run: it overwrites the stored artefacts and re-marks delivered.
// Never throws — delivery failures are logged so the caller (a webhook or admin
// action) can still succeed and be reconciled later.
export async function finalizePaidDocument(documentId: string): Promise<FinalizeResult> {
  const doc = await getDocumentById(documentId);
  if (!doc || !doc.sku) return UNFINALIZED;

  try {
    const rendered = renderForSku(doc.sku, doc.input_json, {
      reference: doc.id,
      generated_at: new Date().toISOString()
    });
    const [pdf, docx] = await Promise.all([
      renderDocumentPdf(rendered),
      renderDocumentDocx(rendered)
    ]);
    const uploaded = await uploadDocumentArtefacts({
      userId: doc.user_id,
      documentId: doc.id,
      pdf,
      docx
    });

    let lawyerReviewId: string | null = null;
    if (doc.addon_lawyer_review) {
      const review = await createLawyerReview({ userId: doc.user_id, documentId: doc.id });
      lawyerReviewId = review?.id ?? null;
    }

    await updateDocumentDelivered({
      documentId: doc.id,
      pdfUrl: uploaded.pdfUrl,
      docxUrl: uploaded.docxUrl,
      lawyerReviewId
    });

    const contact = await getUserContact(doc.user_id);
    if (contact?.email && uploaded.pdfUrl) {
      await sendEmail({
        to: contact.email,
        subject: "Your LegalDesk document is ready",
        html: renderDeliveryEmail({
          name: contact.name ?? "there",
          sku: doc.sku,
          pdfUrl: uploaded.pdfUrl,
          docxUrl: uploaded.docxUrl,
          lawyerReview: !!lawyerReviewId
        }),
        attachments: [{ filename: `${doc.sku}.pdf`, content: pdf }]
      });
    }
    if (contact?.phone) {
      await sendWhatsAppDocument({
        to_phone: contact.phone,
        campaign_name: "document_delivery",
        user_name: contact.name ?? "Customer",
        template_params: [doc.sku],
        media_url: uploaded.pdfUrl ?? undefined
      });
    }

    return {
      finalized: !!uploaded.pdfUrl,
      pdfUrl: uploaded.pdfUrl,
      docxUrl: uploaded.docxUrl,
      lawyerReviewId
    };
  } catch (err) {
    console.error("[payments/finalize] failed", documentId, err);
    return UNFINALIZED;
  }
}

function renderDeliveryEmail(args: {
  name: string;
  sku: string;
  pdfUrl: string;
  docxUrl: string | null;
  lawyerReview: boolean;
}): string {
  const reviewLine = args.lawyerReview
    ? "<p>You added the lawyer-review add-on. A qualified advocate will review your document and get back to you within 24 hours.</p>"
    : "";
  return `
    <p>Hello ${escapeHtml(args.name)},</p>
    <p>Your <strong>${escapeHtml(args.sku)}</strong> document is ready.</p>
    <ul>
      <li><a href="${args.pdfUrl}">Download PDF</a></li>
      ${args.docxUrl ? `<li><a href="${args.docxUrl}">Download DOCX</a></li>` : ""}
    </ul>
    ${reviewLine}
    <p style="color:#666;font-size:12px;margin-top:24px">
      Generated by LegalDesk AI. Not legal advice. Consult a qualified advocate
      for case-specific opinion.
    </p>
  `;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
