import { redirect } from "next/navigation";
import { TriageChat } from "@/components/triage/triage-chat";
import { getSupabaseServerClient } from "@/lib/supabase/server";

export const metadata = {
  title: "AI triage — LegalDesk AI",
  description: "Plain-language triage for Indian legal situations."
};

export default async function TriagePage() {
  const supa = getSupabaseServerClient();
  let mockMode = false;
  if (supa) {
    const {
      data: { user }
    } = await supa.auth.getUser();
    if (!user) redirect("/auth/login?next=/triage");
  } else {
    mockMode = true;
  }

  return (
    <main className="mx-auto flex max-w-2xl flex-col gap-6 px-6 py-12">
      <header>
        <h1 className="text-2xl font-semibold">Tell us what happened.</h1>
        <p className="mt-2 text-sm text-neutral-600">
          We will return a one-page Case Prep with the likely legal framework
          and the next three steps. This is not legal advice.
        </p>
      </header>

      {mockMode ? (
        <p className="rounded-md border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900">
          Running in mock mode — Supabase auth and Anthropic are not
          configured. Triage output is generated by a deterministic stub.
        </p>
      ) : null}

      <TriageChat />
    </main>
  );
}
